# Generated by Django 5.1 on 2025-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "nacionalidade",
                    models.CharField(max_length=100, verbose_name="Nacionalidade"),
                ),
                (
                    "pseudonimo",
                    models.CharField(max_length=100, verbose_name="Pseudônimo"),
                ),
                (
                    "data_nasc",
                    models.DateField(null=True, verbose_name="Data de nascimento"),
                ),
                (
                    "data_falec",
                    models.DateField(null=True, verbose_name="Data falecimento"),
                ),
            ],
        ),
    ]
